-- 职能表
CREATE TABLE IF NOT EXISTS mes_function (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    code VARCHAR(50) NOT NULL COMMENT '职能编码',
    name VARCHAR(100) NOT NULL COMMENT '职能名称',
    description VARCHAR(255) COMMENT '描述',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_code (code)
) COMMENT='职能管理';

-- 用户表
CREATE TABLE IF NOT EXISTS mes_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    emp_id VARCHAR(50) NOT NULL COMMENT '工号',
    name VARCHAR(100) NOT NULL COMMENT '姓名',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_emp_id (emp_id)
) COMMENT='用户管理';

-- 用户职能关联表
CREATE TABLE IF NOT EXISTS mes_user_function (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    function_id BIGINT NOT NULL COMMENT '职能ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_user_function (user_id, function_id)
) COMMENT='用户职能关联';

-- 物料类型表
CREATE TABLE IF NOT EXISTS mes_material_type (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    code VARCHAR(50) NOT NULL COMMENT '类型编码',
    name VARCHAR(100) NOT NULL COMMENT '类型名称',
    description VARCHAR(255) COMMENT '描述',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_code (code)
) COMMENT='物料类型';

-- 物料表
CREATE TABLE IF NOT EXISTS mes_material (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    code VARCHAR(50) NOT NULL COMMENT '物料编码',
    name VARCHAR(100) NOT NULL COMMENT '物料名称',
    type_id BIGINT COMMENT '物料类型ID',
    supplier VARCHAR(100) COMMENT '供应商',
    spec VARCHAR(100) COMMENT '规格型号',
    unit VARCHAR(20) COMMENT '单位',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_code (code)
) COMMENT='物料管理';

-- 工作台表
CREATE TABLE IF NOT EXISTS mes_workstation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    code VARCHAR(50) NOT NULL COMMENT '工作台编码',
    name VARCHAR(100) NOT NULL COMMENT '工作台名称',
    function_id BIGINT COMMENT '绑定职能ID',
    user_id BIGINT COMMENT '绑定用户ID',
    current_material_code VARCHAR(50) COMMENT '当前物料编码',
    last_material_code VARCHAR(50) COMMENT '上一个物料编码',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_code (code)
) COMMENT='工作台管理';

-- 流程定义表
CREATE TABLE IF NOT EXISTS mes_process (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    code VARCHAR(50) NOT NULL COMMENT '流程编码',
    name VARCHAR(100) NOT NULL COMMENT '流程名称',
    description VARCHAR(255) COMMENT '描述',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_code (code)
) COMMENT='流程定义';

-- 流程节点表
CREATE TABLE IF NOT EXISTS mes_process_node (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    process_id BIGINT NOT NULL COMMENT '流程ID',
    node_name VARCHAR(100) NOT NULL COMMENT '节点名称',
    function_id BIGINT COMMENT '绑定职能ID',
    sequence INT DEFAULT 0 COMMENT '顺序',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='流程节点';

-- 供应商表
CREATE TABLE IF NOT EXISTS mes_supplier (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    code VARCHAR(50) NOT NULL COMMENT '供应商编码',
    name VARCHAR(100) NOT NULL COMMENT '供应商名称',
    contact_person VARCHAR(50) COMMENT '联系人',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    address VARCHAR(255) COMMENT '地址',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_code (code)
) COMMENT='供应商管理';

-- 供应商物料关联表
CREATE TABLE IF NOT EXISTS mes_supplier_material (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    material_id BIGINT NOT NULL COMMENT '物料ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_supplier_material (supplier_id, material_id)
) COMMENT='供应商物料关联';

-- 打印机表
CREATE TABLE IF NOT EXISTS mes_printer (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    code VARCHAR(50) NOT NULL COMMENT '打印机编码',
    name VARCHAR(100) NOT NULL COMMENT '打印机名称',
    ip_address VARCHAR(50) NOT NULL COMMENT 'IP地址',
    port INT DEFAULT 9100 COMMENT '端口号',
    description VARCHAR(255) COMMENT '描述',
    status INT DEFAULT 1 COMMENT '状态 1:启用 0:禁用',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_code (code)
) COMMENT='打印机管理';

-- 打印模板表
CREATE TABLE IF NOT EXISTS mes_print_template (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    code VARCHAR(50) NOT NULL COMMENT '模板编码',
    name VARCHAR(100) NOT NULL COMMENT '模板名称',
    material_id BIGINT NOT NULL COMMENT '关联物料ID',
    config_json TEXT COMMENT '模板配置(JSON)',
    description VARCHAR(255) COMMENT '描述',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_code (code)
) COMMENT='打印模板管理';
